<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-39GVIKO" failures="1" tests="7" name="vishal.RestAssured.Booking" time="15.299" errors="0" timestamp="2022-05-20T12:10:27 IST" skipped="0">
  <testcase classname="vishal.RestAssured.Booking" name="createBooking" time="1.287"/>
  <system-out/>
  <testcase classname="vishal.RestAssured.Booking" name="createBooking" time="1.278"/>
  <system-out/>
  <testcase classname="vishal.RestAssured.Booking" name="deleteBooking" time="3.400">
    <failure message="expected:&lt;HTTP/1.1 [201 Creat]ed&gt; but was:&lt;HTTP/1.1 [405 Method Not Allow]ed&gt;" type="org.junit.ComparisonFailure">
      <![CDATA[org.junit.ComparisonFailure: expected:<HTTP/1.1 [201 Creat]ed> but was:<HTTP/1.1 [405 Method Not Allow]ed>
at org.junit.Assert.assertEquals(Assert.java:125)
at org.junit.Assert.assertEquals(Assert.java:147)
at vishal.RestAssured.Booking.deleteBooking(Booking.java:98)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- deleteBooking -->
  <system-out/>
  <testcase classname="vishal.RestAssured.Booking" name="createBooking" time="1.259"/>
  <system-out/>
  <testcase classname="vishal.RestAssured.Booking" name="partialUpdateBooking" time="2.531"/>
  <system-out/>
  <testcase classname="vishal.RestAssured.Booking" name="updateBooking" time="1.533"/>
  <system-out/>
  <testcase classname="vishal.RestAssured.Booking" name="createBooking" time="4.011"/>
  <system-out/>
</testsuite> <!-- vishal.RestAssured.Booking -->
